// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVpYI0BqwZ-jX2huznn_UqKqF5owB1ai4',
    appId: '1:145914157424:web:fb551b29fcb5945097d7b5',
    messagingSenderId: '145914157424',
    projectId: 'note-application-daeef',
    authDomain: 'note-application-daeef.firebaseapp.com',
    storageBucket: 'note-application-daeef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZtL5bkFgNWcpwMsrkJZp12dMrQvrwhI4',
    appId: '1:145914157424:android:7f2689955c24ba8a97d7b5',
    messagingSenderId: '145914157424',
    projectId: 'note-application-daeef',
    storageBucket: 'note-application-daeef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXdnhum0iUbhRcnkZWb8IL-aIh90zqHks',
    appId: '1:145914157424:ios:8ebaa002d170c20297d7b5',
    messagingSenderId: '145914157424',
    projectId: 'note-application-daeef',
    storageBucket: 'note-application-daeef.firebasestorage.app',
    iosBundleId: 'com.example.notesharingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXdnhum0iUbhRcnkZWb8IL-aIh90zqHks',
    appId: '1:145914157424:ios:8ebaa002d170c20297d7b5',
    messagingSenderId: '145914157424',
    projectId: 'note-application-daeef',
    storageBucket: 'note-application-daeef.firebasestorage.app',
    iosBundleId: 'com.example.notesharingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVpYI0BqwZ-jX2huznn_UqKqF5owB1ai4',
    appId: '1:145914157424:web:a820e0d9b17138e497d7b5',
    messagingSenderId: '145914157424',
    projectId: 'note-application-daeef',
    authDomain: 'note-application-daeef.firebaseapp.com',
    storageBucket: 'note-application-daeef.firebasestorage.app',
  );
}
